Algoritmo "Troca de bola entre as duas mãos."
//  
//  

// Descrição   : Realiza a troca de bola de uma mão para outra.
// Autor(a)    : Tiago Galhoto
// Data atual  : 06/05/2026

Var
   // Seção de Declarações das variáveis

   mao : inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   
   mao <- 0
   Enquanto (mao <= 5) faca
      escreval(mao)
      mao <- mao + 1
   FimEnquanto

Fimalgoritmo