Algoritmo "Conte até 10"

// Descrição   : Um contador inícia em 0 e finaliza a contagem em 10.
// Autor(a)    : Tiago Galhoto
// Data atual  : 06/05/2026
Var
   // Seção de Declarações das variáveis

   contador, mao : inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   contador <- 0

   Enquanto (contador <= 10) faca
      escreval(contador)
      contador <- contador + 1
   FimEnquanto
   escreval("Terminei De Contar")

Fimalgoritmo